version: "1.0"
services:
  # frontend:
  #   build:
  #     context: ./packages/frontend
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     NEXT_PUBLIC_API_URL: http://backend:8080

  # backend:
  #   build:
  #     context: ./packages/backend
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - database
  #   environment:
  #     DB_USER: admin
  #     DB_PASSWORD: admin
  #     DB_NAME: univ
  #     DB_HOST: database
  #     DB_PORT: 5432
  #     PORT: 8080

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: univ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
